### ISSUE TITLE
Remove hard-coding database name, maybe use database name from the MongoDB URI?

### ISSUE THREAD

**Issue by nomkhonwaan** [nomkhonwaan/blog-v2#67]
Basically, I'm hard-coding my database name at 

https://github.com/nomkhonwaan/myblog/blob/main/cmd/myblog-server/app/server.go#L107

It might be a good idea to replace this hard-coding string with CLI params.

**Comment by korde96** [comment]
Hey, @nomkhonwaan! seems like a minor fix
should I take this up? would love to help

**Comment by nomkhonwaan** [comment]
> Hey, @nomkhonwaan! seems like a minor fix
> should I take this up? would love to help

yes, please :)

**Comment by korde96** [comment]
cool, 
will get right on.
just to confirm, just substituting the db name with a config from viper should do it, right?

**Comment by korde96** [comment]
@nomkhonwaan would you minf adding the hacktoberfest topic to the repo. I think that's a requirement for these to counted as a valid PR. thanks!

**Comment by nomkhonwaan** [comment]
> @nomkhonwaan would you minf adding the hacktoberfest topic to the repo. I think that's a requirement for these to counted as a valid PR. thanks!

Done :)
